nelmio_api_doc:
    documentation:
        info:
            title: URL shortener
            description: A simple URL shortener
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
